# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      all:
        patterns:
          - "*"
    ignore:
      # Typescript 6 is incompatible with @typescript-eslint/eslint-plugin
      # https://github.com/typescript-eslint/typescript-eslint/issues/12123
      - dependency-name: typescript
        versions: [ ">=6.0.0" ]
