name: Deploy Jobs

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      id:
        description: 'Id of the IaC deployment. Leave blank for the default prod deployment'
        default: ''
        type: string
      env:
        description: 'Deployment environment'
        default: 'nonprod'
        type: choice
        options:
          - nonprod
          - prod

permissions:
  id-token: write
  contents: read
  issues: write

env:
  ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
  TFSTATE_FILE: ${{ inputs.id == '' && 'shovel.tfstate' || 'shovel-${{ inputs.id }}.tfstate' }}

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.id == '' && 'prod' || 'nonprod' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'

    - name: Build Project
      run: |
        npm install 
        npm run build
        npm prune --omit=dev

    - name: Checkout Terraform
      uses: actions/checkout@v3
      with:
        repository: 'ordinal-fomojis/ProjectAlkanes-IAC'
        path: 'terraform'
        token: ${{ secrets.ALKANES_IAC_PAT }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    - name: Get Terrform Outputs
      id: tf-outputs
      run: |
        terraform init -backend-config="key=${{ env.TFSTATE_FILE }}"
        echo "prod_name=$(echo $function_app_name | jq -r '."prod"')" >> $GITHUB_OUTPUT
        echo "nonprod_name=$(echo $function_app_name | jq -r '."nonprod"')" >> $GITHUB_OUTPUT
      working-directory: terraform
    
    - name: Clean Up Terraform
      run: |
        rm -rf terraform
    
    - name: Deploy Nonprod
      uses: Azure/functions-action@v1
      if: inputs.env != 'prod'
      with:
        app-name: ${{ steps.tf-outputs.outputs.nonprod_name }}
        respect-funcignore: true

    - name: Deploy Prod
      if: github.ref_name == 'main' && inputs.env == 'prod'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ steps.tf-outputs.outputs.prod_name }}
        respect-funcignore: true
